// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ptypes/msg.proto

package ptypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BasicMessage struct {
	SenderName           string   `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Oid                  uint32   `protobuf:"varint,3,opt,name=oid,proto3" json:"oid,omitempty"`
	Timestamp            uint32   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicMessage) Reset()         { *m = BasicMessage{} }
func (m *BasicMessage) String() string { return proto.CompactTextString(m) }
func (*BasicMessage) ProtoMessage()    {}
func (*BasicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_edd8a2b1cd2058e2, []int{0}
}

func (m *BasicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicMessage.Unmarshal(m, b)
}
func (m *BasicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicMessage.Marshal(b, m, deterministic)
}
func (m *BasicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicMessage.Merge(m, src)
}
func (m *BasicMessage) XXX_Size() int {
	return xxx_messageInfo_BasicMessage.Size(m)
}
func (m *BasicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BasicMessage proto.InternalMessageInfo

func (m *BasicMessage) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *BasicMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BasicMessage) GetOid() uint32 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *BasicMessage) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*BasicMessage)(nil), "BasicMessage")
}

func init() { proto.RegisterFile("ptypes/msg.proto", fileDescriptor_edd8a2b1cd2058e2) }

var fileDescriptor_edd8a2b1cd2058e2 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xa9, 0x2c,
	0x48, 0x2d, 0xd6, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xaa, 0xe4, 0xe2,
	0x71, 0x4a, 0x2c, 0xce, 0x4c, 0xf6, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x92, 0xe7, 0xe2,
	0x2e, 0x4e, 0xcd, 0x4b, 0x49, 0x2d, 0x8a, 0xcf, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0xe2, 0x82, 0x08, 0xf9, 0x25, 0xe6, 0xa6, 0x0a, 0x49, 0x70, 0xb1, 0xe7, 0x42, 0xd4,
	0x4a, 0x30, 0x81, 0x25, 0x61, 0x5c, 0x21, 0x01, 0x2e, 0xe6, 0xfc, 0xcc, 0x14, 0x09, 0x66, 0x05,
	0x46, 0x0d, 0xde, 0x20, 0x10, 0x53, 0x48, 0x86, 0x8b, 0xb3, 0x24, 0x33, 0x37, 0xb5, 0xb8, 0x24,
	0x31, 0xb7, 0x40, 0x82, 0x05, 0x2c, 0x8e, 0x10, 0x70, 0xe2, 0x88, 0x62, 0x83, 0x38, 0x27, 0x89,
	0x0d, 0xec, 0x16, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x2a, 0x3a, 0x18, 0x9f, 0x00,
	0x00, 0x00,
}
